apiVersion: app/v1
kind: PersistentVolume
metadata: 
  name: bdmonedas-pv
spec:
  capacity:
    storage: 1Gi
  sccessModes:
    -ReadWriteOnce
  hostPath:
    path: "/data/postgres"
  persistentVolumeReclaimPolicy: Delete